---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: '^chart/.*/templates/.*\.yaml$'
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: forbid-new-submodules
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: go-mod-tidy
      - id: go-unit-tests
      - id: golangci-lint

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs
        exclude: '(Makefile|\.mk|\.go|go\.mod)$'

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint
        args: [--ignore=DL3008, --ignore=DL3009, --ignore=DL3059, --ignore=DL3062, --ignore=DL4006, --ignore=SC2046]

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: go-build
        name: go-build
        entry: make build
        language: system
        files: \.go$
        pass_filenames: false

      - id: go-test-coverage
        name: go-test-coverage
        entry: make test-coverage
        language: system
        files: \.go$
        pass_filenames: false

      - id: go-security-scan
        name: go-security-scan
        entry: make security-scan
        language: system
        files: \.go$
        pass_filenames: false
        stages: [pre-commit]

      - id: manifest-validation
        name: validate-k8s-manifests
        entry: make validate-manifests
        language: system
        files: \.ya?ml$
        pass_filenames: false

      - id: prevent-package-files
        name: prevent-package-files
        entry: 'Package files should not be committed (use .gitignore)'
        language: fail
        files: '\.(tgz|tar\.gz|zip|jar|war|deb|rpm)$'

fail_fast: false
